CREATE TABLE user (
	ID INT NOT NULL AUTO_INCREMENT,
	username VARCHAR(14),
	nickname VARCHAR(14),
	age INT,
	gender VARCHAR(24),
	phoneNumber VARCHAR(15),
	email VARCHAR(72),
	password VARCHAR(60),
	registered TINYINT(1) NOT NULL,
	UNIQUE(username),
	PRIMARY KEY (ID)
);

CREATE TABLE counsellor (
	ID INT NOT NULL AUTO_INCREMENT,
	firstName VARCHAR(30) NOT NULL,
	lastName VARCHAR(30) NOT NULL,
	email VARCHAR(256) NOT NULL,
	password VARCHAR(60) NOT NULL,
	UNIQUE(email),
	PRIMARY KEY (ID)
);

CREATE TABLE session (
	ID INT NOT NULL AUTO_INCREMENT,
	beginTime TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	endTime TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	counsellorID INT NOT NULL,
	userID INT,
	PRIMARY KEY (ID),
	FOREIGN KEY (userID) REFERENCES user(ID)
);

CREATE TABLE message (
	ID INT NOT NULL AUTO_INCREMENT,
	sessionID INT NOT NULL,
	messageTime TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	counsellorID INT NOT NULL,
	userID INT NOT NULL,
	messageContent TEXT NOT NULL,
	fromCounsellor TINYINT(1) NOT NULL,
	fromTwilio TINYINT(1) NOT NULL,
	PRIMARY KEY (ID),
	FOREIGN KEY (sessionID) REFERENCES session(ID),
	FOREIGN KEY (counsellorID) REFERENCES counsellor(ID),
	FOREIGN KEY (userID) REFERENCES user(ID)
);
