CREATE TABLE twilio (
	ID INT NOT NULL AUTO_INCREMENT,
	email VARCHAR(256) NOT NULL,
	twilioPhoneNumber VARCHAR(15),
	accountSid VARCHAR(34),
	authToken VARCHAR(32),
	UNIQUE(email),
	UNIQUE(twilioPhoneNumber),
	UNIQUE(authToken),
	PRIMARY KEY (ID)
);

CREATE TABLE database_admin (
	host VARCHAR(256) NOT NULL,
	user VARCHAR(32) NOT NULL,
	password TEXT NOT NULL,
	dbName VARCHAR(64) NOT NULL,
	PRIMARY KEY (dbName)
);

CREATE TABLE no_account_user (
	ID INT NOT NULL AUTO_INCREMENT,
	phoneNumber VARCHAR(15),
	PRIMARY KEY (ID)
);

CREATE TABLE user (
	ID INT NOT NULL AUTO_INCREMENT,
	username VARCHAR(14) NOT NULL,
	age INT,
	gender VARCHAR(24) NOT NULL,
	phoneNumber VARCHAR(15) NOT NULL,
	email VARCHAR(72) NOT NULL,
	password VARCHAR(60) NOT NULL,
	UNIQUE(username),
	PRIMARY KEY (ID)
);

CREATE TABLE counsellor (
	ID INT NOT NULL AUTO_INCREMENT,
	firstName VARCHAR(30) NOT NULL,
	lastName VARCHAR(30) NOT NULL,
	email VARCHAR(256) NOT NULL,
	password VARCHAR(60) NOT NULL,
	UNIQUE(email),
	PRIMARY KEY (ID)
);

CREATE TABLE chatroom (
	ID INT NOT NULL AUTO_INCREMENT,
	counsellorID INT NOT NULL,
	userID INT NOT NULL,
	PRIMARY KEY (ID)
);

CREATE TABLE session (
	ID INT NOT NULL AUTO_INCREMENT,
	beginTime TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	endTime TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	counsellorID INT NOT NULL,
	userID INT,
	PRIMARY KEY (ID)
);

CREATE TABLE message (
	ID INT NOT NULL AUTO_INCREMENT,
	chatroomID INT NOT NULL,
	sessionID INT NOT NULL,
	messageTime TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	counsellorID INT NOT NULL,
	userID INT NOT NULL,
	messageContent TEXT NOT NULL,
	fromCounsellor TINYINT(1) NOT NULL,
	fromTwilio TINYINT(1) NOT NULL,
	PRIMARY KEY (ID)
);
